build(tsc): Replace webpack with tsc
onyxjs/base pull request #11
Opened 2019-11-02 14:24 UTC by ElijahKotyluk

2019-11-02 15:26 UTC, dsseng requested changes
Please  update snapshots

2019-11-03 19:09 UTC, sh7dm commented on packages/core/src/test.ts
> -      if (error instanceof ExpectError) {
This should be left in place. (if some assert failed, test is marked as failed, if just an error happened: errored). but maybe we should remove errored status in future.

2019-11-03 19:09 UTC, sh7dm commented on packages/core/tsconfig.json
> +    "module": "CommonJS",
```suggestion
    "module": "commonjs",
```

2019-11-03 19:09 UTC, sh7dm commented on packages/matchers/tsconfig.json
> +    "module": "CommonJS",
```suggestion
    "module": "commonjs",
```

2019-11-03 19:09 UTC, sh7dm commented on packages/mock/tsconfig.json
> +    "module": "CommonJS",
```suggestion
    "module": "commonjs",
```

2019-11-04 19:18 UTC, dsseng requested changes
please update snapshots

2019-11-04 19:22 UTC, ElijahKotyluk commented
Snapshots are already updated.

2019-11-04 19:24 UTC, sh7dm commented
They should be updated once more since you fixed `ExpectError` issue.

2019-11-08 23:43 UTC, merged