refactor(Core): Major refactor of Core package.
onyxjs/base pull request #14
Opened 2019-12-30 06:50 UTC by ElijahKotyluk

2020-02-05 18:45 UTC, sh7dm commented on packages/core/test/runnable.spec.ts
> +  const opts = { todo: false, skip: false };
maybe rename it to `defaultOpts`?

2020-02-05 18:46 UTC, ElijahKotyluk commented on packages/core/test/runnable.spec.ts
> +  const opts = { todo: false, skip: false };
Very good point, will do.

2020-02-07 13:10 UTC, sh7dm commented on packages/core/src/interface.ts
> +const root = new Suite('root', { bail: false, skip: false, todo: false }, null);
We need to develop a way how bail is propagated, but this is probably an interface feature

2020-02-07 16:43 UTC, ElijahKotyluk commented on packages/core/src/interface.ts
> +const root = new Suite('root', { bail: false, skip: false, todo: false }, null);
We can do it in this PR or open up one focused on bail propagation, which would you prefer?

2020-02-08 10:31 UTC, sh7dm commented on packages/core/src/interface.ts
> +const root = new Suite('root', { bail: false, skip: false, todo: false }, null);
idk for sure

2020-02-08 10:43 UTC, ElijahKotyluk commented on packages/core/src/interface.ts
> +const root = new Suite('root', { bail: false, skip: false, todo: false }, null);
I think we can add bail in the very near future. We can probably focus on it in when we do the runner since that will basically be the root. But we do have a couple options for how to handle this problem, one we can pass it as a runner option and when the runner or a child suite gets it's first fail which will be emitted from a runnable(test) just stop further execution.

2020-02-08 11:46 UTC, sh7dm commented on packages/core/src/interface.ts
> +const root = new Suite('root', { bail: false, skip: false, todo: false }, null);
yea, let's just revert bail for now.

2020-03-07 09:18 UTC, sh7dm commented on packages/core/test/runner.spec.ts
> +  // it('should emit fail with errors', () => {
we removed that

2020-03-07 09:21 UTC, ElijahKotyluk commented on packages/core/test/runner.spec.ts
> +  // it('should emit fail with errors', () => {
That's weird, I'll remove it.

2020-03-07 09:22 UTC, sh7dm commented
TODO:
- [ ] Timeout support
- [ ] Bail support
- [ ] Hooks

2020-03-07 11:58 UTC, sh7dm commented on packages/core/src/suite.ts
> +        }
```suggestion
        failed = true;

        if (options && options.bail) {
          if (typeof options.bail === 'number' && ++this.failed >= options.bail) {
            return this.doFail();
          } else if (options.bail === true) {
            return this.doFail();
          }
        }
```

2020-03-12 05:06 UTC, sh7dm commented on packages/core/src/utils.ts
> +export async function asyncTimeout(ms: number, promise: () => Promise<any>): Promise<any> {
What's about type inference? Like this:
```suggestion
export async function asyncTimeout<T>(ms: number, promise: () => Promise<T>): Promise<T> {
```
Also, I think it is more logical to use just Promise, not async fn for promise arg

2020-03-12 05:36 UTC, ElijahKotyluk commented on packages/core/src/utils.ts
> +export async function asyncTimeout(ms: number, promise: () => Promise<any>): Promise<any> {
Thank you for catching that. I've been so messed up with this timeout situation :/

2020-03-12 13:20 UTC, sh7dm commented on packages/core/src/utils.ts
> +export async function asyncTimeout(ms: number, promise: () => Promise<any>): Promise<any> {
what's about this:

2020-03-16 16:11 UTC, sh7dm commented on packages/core/src/test.ts
> +      });
I think this can be simplified using `await` and `try`/`catch`.

2020-03-16 21:48 UTC, ElijahKotyluk commented on packages/core/src/test.ts
> +      });
Will work on it.

2020-04-01 06:53 UTC, sh7dm commented on packages/core/src/test.ts
> +  public async asyncRun(options?: Partial<RunOptions>): Promise<Result> {
```suggestion
  public async run(options?: Partial<RunOptions>): Promise<Result> {
```

2020-04-03 15:15 UTC, dsseng commented on packages/core/src/runnable.ts
> +   * @description Run `Runnable` instance asynchronously.
```suggestion
   * @description Run `Runnable` instance.
```

2020-04-03 15:15 UTC, dsseng commented on packages/core/src/runnable.ts
> +   * @description Run `Runnable` instance asynchronously.
```suggestion
   * @description Run `Runnable` instance.
```

2020-04-03 15:15 UTC, dsseng commented on packages/core/src/runnable.ts
>     * @return {Promise}
```suggestion
   * @return {Promise<Result>}
```

2020-04-03 15:15 UTC, dsseng commented on packages/core/src/runner.ts
> +  public async run() {
Should it be a JSDoc here?

2020-04-03 15:15 UTC, dsseng commented on packages/core/src/suite.ts
> +export interface Stats {
Maybe we should rename it to `SuiteStats`?

2020-04-03 15:15 UTC, dsseng commented on packages/core/src/suite.ts
> +  public async invokeAsyncHook(name: HookName) {
`invokeAsyncHook` -> `invokeHook`, since no sync variant is present now.

2020-04-03 15:15 UTC, dsseng commented on packages/core/src/suite.ts
> +  public async invokeAsyncHook(name: HookName) {
JSDoc comment is required too

2020-04-03 15:15 UTC, dsseng commented on packages/core/src/suite.ts
> +  public addChildren(...children: Runnable[]): void {
```suggestion
   * @returns {void}
   */
  public addChildren(...children: Runnable[]) {
```

2020-04-03 15:15 UTC, sh7dm commented on packages/core/src/suite.ts
> +   * @description Runs a `Suite` instance asynchronously returning a `Result`:
No sync variant is supported
```suggestion
   * @description Runs a `Suite` instance returning a `Result`:
```

2020-04-03 15:15 UTC, sh7dm commented on packages/core/src/suite.ts
> +              throw new BailError('bailed');
Probably there should be some info, e.g. which tests failed. What do you think?

2020-04-03 15:15 UTC, sh7dm commented on packages/core/src/suite.ts
> +    };
```suggestion
    const childrenList = this.flatten(this.children);
    return {
      done: childrenList.filter((c) => c.result.isDone()).length,
      failed: childrenList.filter((c) => c.result.status === Status.Failed).length,
      passed: childrenList.filter((c) => c.result.status === Status.Passed).length,
      pending: childrenList.filter((c) => c.result.status === Status.Pending).length,
      running: childrenList.filter((c) => c.result.status === Status.Running).length,
      skipped: childrenList.filter((c) => c.result.status === Status.Skipped).length,
      time: this.time,
      todo: childrenList.filter((c) => c.result.status === Status.Todo).length,
      total: childrenList.length,
    };
```

2020-04-03 15:15 UTC, sh7dm commented on packages/core/src/test.ts
> +export type testFn = () => void | Promise<any>;
Just a style change to emphasize the correct type. Did I do this correctly :sweat_smile: ?
```suggestion
export type testFn = () => (void | Promise<any>);
```

2020-04-03 15:15 UTC, sh7dm commented on packages/core/src/test.ts
> +  public type = RunnableTypes.Test;
```suggestion
  public type: RunnableTypes.Test = RunnableTypes.Test;
```

2020-04-03 15:15 UTC, sh7dm commented on packages/core/src/test.ts
> +export type testFn = () => void | Promise<any>;
Also, type names should be capitalized: `TestFn`

2020-04-03 15:15 UTC, sh7dm commented on packages/core/src/test.ts
> +   * Run a `Test` instance asynchronously return `Runnable` status:
```suggestion
   * Run a `Test` instance, return `Runnable` status:
```

2020-04-03 15:40 UTC, ElijahKotyluk commented on packages/core/src/test.ts
> +      });
@TODO for later

2020-04-03 15:53 UTC, ElijahKotyluk commented on packages/core/src/suite.ts
> +export interface Stats {
I think so too, more descriptive name.

2020-04-03 19:13 UTC, ElijahKotyluk commented on packages/core/src/suite.ts
> +export interface Stats {
aefd1d0

2020-04-03 19:13 UTC, ElijahKotyluk commented on packages/core/src/suite.ts
> +  public async invokeAsyncHook(name: HookName) {
aefd1d0

2020-04-03 19:14 UTC, ElijahKotyluk commented on packages/core/src/suite.ts
> +   * @description Runs a `Suite` instance asynchronously returning a `Result`:
aefd1d0

2020-04-06 18:22 UTC, sh7dm commented on packages/core/src/result.ts
> +   * @description Adds messages to the internal messages if the `Runnable` has completed.
hmm, it does only when it's __not__ completed

2020-04-06 19:17 UTC, ElijahKotyluk commented on packages/core/src/result.ts
> +   * @description Adds messages to the internal messages if the `Runnable` has completed.
Oops, thanks for catching that.

2020-06-14 11:35 UTC, dsseng requested changes

2020-06-14 11:35 UTC, sh7dm commented on packages/core/src/suite.ts
> +   * @description Add one or more `Runnable` instances to `Suite.children`.
```suggestion
   * @description Add one or more child `Runnable` instances.
```

2020-06-14 11:35 UTC, sh7dm commented on packages/core/src/suite.ts
> +    const childrenList = this.flatten(this.children);
Maybe we should refactor this this way: all suites collect stats from child tests and suites

2020-06-14 11:35 UTC, sh7dm commented on packages/core/src/test.ts
> + * @description Checks if the passed value is a `Runnable` instance of type `Test`.
```suggestion
 * @description Checks if the passed value is a `Test` instance.
```

2020-06-14 11:35 UTC, sh7dm commented on packages/core/src/test.ts
> + * @description Checks if the passed value is a `Runnable` instance of type `Test`.
or:
```suggestion
 * @description Checks if the passed `Runnable` value is a `Test` instance.
```

2020-08-26 15:49 UTC, ElijahKotyluk commented on packages/core/src/suite.ts
> +    const childrenList = this.flatten(this.children);
I opened an issue for this, I will take a look at this and work on it throughout the week. Let's wrap this up and merge this if everything else looks good to you.

2020-09-29 06:20 UTC, merged